{% set version = "0.6.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cards
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cards_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cards/cards_{{ version }}.tar.gz
  sha256: 6cb9d4fd5168557f799dd88a09c525425bf7e85162253e18ca502096a686bfd9

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.6.1
    - r-dplyr >=1.1.2
    - r-glue >=1.6.2
    - r-lifecycle >=1.0.3
    - r-rlang >=1.1.1
    - r-tidyr >=1.3.0
    - r-tidyselect >=1.2.0
  run:
    - r-base
    - r-cli >=3.6.1
    - r-dplyr >=1.1.2
    - r-glue >=1.6.2
    - r-lifecycle >=1.0.3
    - r-rlang >=1.1.1
    - r-tidyr >=1.3.0
    - r-tidyselect >=1.2.0

test:
  commands:
    - $R -e "library('cards')"           # [not win]
    - "\"%R%\" -e \"library('cards')\""  # [win]

about:
  home: https://insightsengineering.github.io/cards/
  dev_url: https://github.com/insightsengineering/cards
  license: Apache-2.0
  summary: Construct CDISC (Clinical Data Interchange Standards Consortium) compliant Analysis Results Data objects. These objects are used and re-used to construct summary tables, visualizations, and written reports. The package also exports utilities for working with these objects and creating new Analysis Results Data
    objects.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
